version = 1

[[analyzers]]
name = "kotlin"

  [analyzers.meta]
  runtime_version = "21"
  language_version = "1.7"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "17"

[[transformers]]
name = "google-java-format"

[[transformers]]
name = "ktlint"