blank_issues_enabled: false
contact_links:
  - name: Jellyfin documentation
    url:  https://jellyfin.org/docs/general/getting-help.html
    about: Our documentation contains lots of help for common issues
  - name: Jellyfin contact
    url: https://jellyfin.org/contact/
    about: Our community is ready to help you get started with Jellyfin
