name: Feature request
description: Request a new feature
labels:
  - enhancement
body:
  - type: checkboxes
    id: before-posting
    attributes:
      label: "This request respects the following points:"
      description: All conditions are **required**.
      options:
        - label: This request is **not** already on [GitHub](https://github.com/jellyfin/jellyfin-androidtv/labels/enhancement) _(I've searched it)_.
          required: true
        - label: I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
          required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the feature you'd like
      description: |
        A clear and concise description of what you want to request.
        You can also attach screenshots or screen recordings to help explain your request.
    validations:
      required: true
