package org.jellyfin.androidtv.constants;

public enum QueryType {
    Items,
    NextUp,
    Views,
    Season,
    Upcoming,
    SimilarSeries,
    SimilarMovies,
    StaticPeople,
    StaticChapters,
    StaticServers,
    Users,
    Search,
    Specials,
    Trailers,
    LiveTvChannel,
    LiveTvProgram,
    LiveTvRecording,
    LiveTvRecordingGroup,
    StaticItems,
    Persons,
    StaticAudioQueueItems,
    AlbumArtists,
    AudioPlaylists,
    ContinueWatching,
    LatestItems,
    SeriesTimer,
    Premieres
}
