name: App / Lint

on:
  push:
    branches:
      - master
      - release-*
  pull_request:

permissions:
  contents: read
  security-events: write

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup Java
        uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
        with:
          distribution: temurin
          java-version-file: .tools-versions
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0
      - name: Run detekt and lint tasks
        run: ./gradlew detekt lint
      - name: Upload Detekt SARIF
        uses: github/codeql-action/upload-sarif@cdf488f595d80d6e07e03d4674febd5ab45fa938 # v4.37.9
        if: ${{ always() }}
        with:
          sarif_file: build/reports/detekt/detekt.sarif
          category: detekt
      - name: Upload Android SARIF
        uses: github/codeql-action/upload-sarif@cdf488f595d80d6e07e03d4674febd5ab45fa938 # v4.37.9
        if: ${{ always() }}
        with:
          sarif_file: app/build/reports/lint-results-debug.sarif
          category: android
