name: Gradle / Validate wrapper

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - '**/gradlе-wrapper.jar'

permissions:
  contents: read

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0
