name: Repo / Label merge conflict

on:
  push:
  pull_request_target:
    types:
      - synchronize

jobs:
  triage:
    name: Triage
    runs-on: ubuntu-24.04
    if: ${{ contains(github.repository_owner, 'jellyfin') }}
    steps:
      - uses: eps1lon/actions-label-merge-conflict@0273be72a0bbd58fcd71d0d6c02c209b50d1e5e1 # v3.1.0
        with:
          dirtyLabel: merge conflict
          repoToken: ${{ secrets.JF_BOT_TOKEN }}
