name: Repo / Label merge conflict

on:
  push:
  pull_request_target:
    types:
      - synchronize

jobs:
  triage:
    name: Triage
    runs-on: ubuntu-22.04
    if: ${{ contains(github.repository_owner, 'jellyfin') }}
    steps:
      - uses: eps1lon/actions-label-merge-conflict@e62d7a53ff8be8b97684bffb6cfbbf3fc1115e2e # v3.0.0
        with:
          dirtyLabel: merge conflict
          repoToken: ${{ secrets.JF_BOT_TOKEN }}
